# Generated by Django 5.0.7 on 2025-02-21 10:09

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=100, unique=True)),
                ('cust_phone', models.CharField(max_length=11, unique=True)),
                ('cust_addess', models.CharField(max_length=100)),
                ('cust_id', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_ID', models.CharField(max_length=100, unique=True)),
                ('tranx_date', models.DateField(default=django.utils.timezone.now)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='model name eg Big Daddu', max_length=100, unique=True)),
                ('model_descr', models.CharField(max_length=100, unique=True)),
                ('model_SKU', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['product_name', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='model name eg Toyota', max_length=100, unique=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='fappy_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=100, unique=True)),
                ('batch_id', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=1, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('date_supplied', models.DateField(default=django.utils.timezone.now)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fappy_app.model')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='model name eg corrolla', max_length=100, unique=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Brand_Name', to='fappy_app.brand')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Brand_Name', to='fappy_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fappy_app.product'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Inward'), ('OUT', 'Outward'), ('Sal', 'Sales'), ('Maint', 'Maintenance')], default='IN', max_length=5)),
                ('quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now=True)),
                ('cus_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fappy_app.customer')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fappy_app.invoice')),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fappy_app.inventory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='model',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('model_name'), name='genre_name_case_insensitive_unique', violation_error_message='Model already exists (case insensitive match)'),
        ),
    ]
