# Generated by Django 5.0.7 on 2025-02-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_name', models.CharField(max_length=11)),
                ('value', models.IntegerField(default=0)),
                ('QuantityProduced', models.IntegerField(default=0)),
                ('gift_picture', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11)),
                ('gift', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('gift_picture', models.ImageField(upload_to='static/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kupian_app.promocode')),
            ],
        ),
        migrations.CreateModel(
            name='Winning_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_name', models.CharField(max_length=11)),
                ('Wcode_point', models.IntegerField(default=0)),
                ('Voucher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kupian_app.promocode')),
            ],
        ),
    ]
