# Generated by Django 5.0.7 on 2025-02-22 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0003_product_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('NGN', 'Naira'), ('GBP', 'Pound'), ('EURO', 'Euro'), ('USD', 'usd')], default='NGN', max_length=50, verbose_name='')),
                ('naira', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='')),
                ('pound', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='')),
                ('euro', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='')),
                ('usd', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fashion_app.category', verbose_name=''),
        ),
    ]
