# Generated by Django 5.0.7 on 2025-02-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0004_category_currency_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name=''),
        ),
    ]
