# Generated by Django 4.2 on 2025-03-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fashion_app", "0006_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="currency",
            field=models.CharField(
                choices=[
                    ("NGN", "Naira"),
                    ("GBP", "Pound"),
                    ("EURO", "Euro"),
                    ("USD", "usd"),
                ],
                default="NGN",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="euro",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="currency",
            name="naira",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="currency",
            name="pound",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="currency",
            name="usd",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
