# Generated by Django 4.2 on 2025-03-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fashion_app", "0007_alter_currency_currency_alter_currency_euro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="euro",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="currency",
            name="naira",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="currency",
            name="pound",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="currency",
            name="usd",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
