# Generated by Django 4.2 on 2025-03-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fashion_app", "0008_alter_currency_euro_alter_currency_naira_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="complete",
            new_name="completed",
        ),
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="date_ordered",
        ),
        migrations.RemoveField(
            model_name="order",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="order",
            name="session_key",
            field=models.CharField(default="a", max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
