# Generated by Django 4.2 on 2025-03-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fashion_app", "0010_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
